####################################################
#
# Welcome to Doxy Jekyll Template
#
# Product Link : https://themeix.com/product/doxy-documentation-website-jekyll-template/
# Version : v4.1.0
#
####################################################

theme: minima
plugins:
  - jekyll-asciidoc
  - jekyll-sitemap
#   - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-redirect-from

# Site settings
title: "Gravitee.io API Platform Documentation"
description: "Home page for Gravitee.io API Platform documentation"
keywords: "Gravitee.io, API Platform, API Management, API Gateway, oauth2, openid, documentation, manual, guide, reference, api, alert, alerting, engine"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.gravitee.io"
# cover_image: "https://themeix.com/wp-content/uploads/dooxy-responsive-html-template-preview.png" # Image will Display in Social Media When share the website
# facebook: "https://www.facebook.com"
twitter: "https://twitter.com/graviteeio"
instagram: "https://www.instagram.com/gravitee"
github: "https://www.github.com/gravitee-io"
linkedin: "https://www.linkedin.com/company/gravitee-io"
# behance: "https://www.behance.com"
reddit: "https://www.reddit.com/user/Graviteeio"
# vimeo: "https://www.vimeo.com"
# dribble: "https://www.dribble.com"
# youtube: "https://www.youtube.com"

## Theme Options
animated_header: ""  #true
# twitter_username: graviteeio
# github_username:  graviteeio

# twitter:
# username: graviteeio

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

site_title: Gravitee.io API Platform Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: GraviteeSource
# this appears in the footer

github_editme_path:
# gravitee-io/gravitee-docs/tree/master/pages/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname:
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - README.adoc
  - CONTRIBUTING.adoc
  - src/
  - node_modules
# these are the files and directories that jekyll will exclude from the build

#feedback_subject_line:
#feedback_email:
# used as a contact email for the Feedback link in the top navigation bar
feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed
# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text
# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

#markdown: kramdown
#kramdown:
# input: GFM
# auto_ids: true
# hard_wrap: false
# syntax_highlighter: rouge

google_analytics: UA-67690250-1

newsletter_api: 'https://newsletter.gravitee.io/'

# toc:
#  min_level: 1
#  max_level: 3
#  no_toc_section_class: no_toc_section
#  list_class: section-nav
#  sublist_class: ''
#  item_class: toc-entry
#  item_prefix: toc-

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

collections:
  docs:
    output: true
    permalink: /:path
    layout: "doc"
  pages:
    output: true
    permalink:
    layout: "page"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true

# these are defaults used for the frontmatter for these file types

# needed for sitemap.xml file only
url: https://docs.gravitee.io

products:
  apim:
    _1x:
      version: 1.30.31
    _3x:
      version: 3.13.1
    ee:
      version: 3.11.0
  am:
    version: 3.13.0
    ee:
      version: 3.11.0
  ae:
    version: 1.4.0
    name: Gravitee.io Alert Engine (AE)
  cli:
    version: 0.3
  cockpit:
    version: 3.11.1

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - doctype=book
    - idseparator=_
    - icons=font
    - allow-uri-read=true
    - imagesdir=/assets/images/
    - source-highlighter=rouge
    - rouge-css=class
    - stylesdir=/assets/css/

algolia:
  application_id: BH4D9OD16A
