# must be in sets of 3

apim:
- name: Publisher Guide
  url: /Guides/apim/current/publisher-guide/introduction.html

- name: Consumer Guide
  url: /Guides/apim/current/consumer-guide/introduction.html

- name: Administration Guide
  url: /Guides/apim/current/administration-guide/organizations-environments.html

apim2:
- name: Developer Guide
  url: /Guides/apim/current/developer-guide/bootstrap.html

am:
- name: User Guide
  url: /Guides/am/current/user-guide/introduction.html

- name: Administration Guide
  url: /Guides/am/current/administration-guide/organizations-environments.html

- name: Developer Guide
  url: /Guides/am/current/developer-guide/bootstrap.html

am2:
- name: Protocols Guide
  url: /Guides/am/current/protocols-guide/introduction.html

ae:
- name: User Guide
  url: /Guides/ae/current/user-guide/definition.html

cockpit:
- name: User Guide
  url: /Guides/cockpit/current/user-guide/register-installations.html
