- title: Get Started
  icon: /assets/images/service-icon2.png
  description: Get up and running with the APIM platform components
  button_label: Learn More
  url: /getstarted.html

- title: Quick Install Guides
  icon: /assets/images/service-icon.png
  description:  Install the platform components with minimum fuss
  button_label: Read Docs
  url: /apim/current/apim_getstarted_quickinstall.html

- title: Tutorials
  icon: /assets/images/service-icon3.png
  description: Have a look at these resources to learn how APIM platform can help you
  button_label: Learn More
  url: /pages/tutorials
